### ISSUE TITLE
La traducción en las páginas distintas al index no funciona

### ISSUE THREAD

**Issue by dappsar** [P4-Games/NoF-LandingPage#18]
**Comportamiento esperado**

Todas las páginas del sitio debería ser traducidas al cambiar el idioma.

**Comportamiento actual**

Las páginas /alpha, /gamma; no se traducen y se observa el siguiente error (en la consola de desarrollo):
```
framework-3b5a00d5d7e8d93b.js:9 Uncaught TypeError: t is not a function
    at onClick (965.643355f429f47e1d.js:1:2837)
    at Object.eV (framework-3b5a00d5d7e8d93b.js:9:14914)
```

**Comment by dappsar** [comment]
Fixed in PR: #43
