### ISSUE TITLE
Mint: Error al intentar mintear una figurita en gamma

### ISSUE THREAD

**Issue by dappsar** [P4-Games/NoF-LandingPage#48]
**Comportamiento actual**

Al querer hacer un minteo de una figurita en gamma, da el siguiente error:

```
{
    "e": {
        "reason": "execution reverted: No tienes esta carta",
        "code": "UNPREDICTABLE_GAS_LIMIT",
        "method": "estimateGas",
        "transaction": {
            "from": "0xC5350d728EaddE9F5537f89D261aAaadFb4dCaEA",
            "to": "0xEefF8D035A60AC3E1456991C2A2C2dEb31C84B76",
            "data": "0xbf400a6a0000000000000000000000000000000000000000000000000000000000000001",
            "accessList": null
        },
        "error": {
            "code": -32603,
            "message": "Internal JSON-RPC error.",
            "data": {
                "code": 3,
                "message": "execution reverted: No tienes esta carta",
                "data": "0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000144e6f207469656e65732065737461206361727461000000000000000000000000"
            },
            "stack": "{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": 3,\n    \"message\": \"execution reverted: No tienes esta carta\",\n    \"data\": \"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000144e6f207469656e65732065737461206361727461000000000000000000000000\"\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:10940)\\n    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:13880)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:14490)\\n    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:49968)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:50970\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:37935\"\n}\n  at i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:10940)\n  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:13880)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:14490)\n  at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:49968)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:50970\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:37935"
        }
    }
}
```

**Comportamiento esperado**

Debería mostrarte un mensaje con el motivo del error. Por ejemplo, si no tienes esa carta para mintear.

**Comment by dappsar** [comment]
Fixed in PR: #87
